//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace moleQule.Face.Hipatia.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("moleQule.Face.Hipatia.Resources.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aviso.
        /// </summary>
        internal static string ADVISE_TITLE {
            get {
                return ResourceManager.GetString("ADVISE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva Carpeta.
        /// </summary>
        internal static string AGENTE_ADD_TITLE {
            get {
                return ResourceManager.GetString("AGENTE_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle de Carpeta:.
        /// </summary>
        internal static string AGENTE_DETAIL_TITLE {
            get {
                return ResourceManager.GetString("AGENTE_DETAIL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Carpeta:.
        /// </summary>
        internal static string AGENTE_EDIT_TITLE {
            get {
                return ResourceManager.GetString("AGENTE_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elija un agente por favor:.
        /// </summary>
        internal static string AGENTE_INPUT_TITLE {
            get {
                return ResourceManager.GetString("AGENTE_INPUT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carpetas.
        /// </summary>
        internal static string AGENTES {
            get {
                return ResourceManager.GetString("AGENTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iQ Hipatia.
        /// </summary>
        internal static string APP_TITLE {
            get {
                return ResourceManager.GetString("APP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Documento.
        /// </summary>
        internal static string DOCUMENTO_ADD_TITLE {
            get {
                return ResourceManager.GetString("DOCUMENTO_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle de Documento:.
        /// </summary>
        internal static string DOCUMENTO_DETAIL_TITLE {
            get {
                return ResourceManager.GetString("DOCUMENTO_DETAIL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Documento:.
        /// </summary>
        internal static string DOCUMENTO_EDIT_TITLE {
            get {
                return ResourceManager.GetString("DOCUMENTO_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elija un documento por favor:.
        /// </summary>
        internal static string DOCUMENTO_INPUT_TITLE {
            get {
                return ResourceManager.GetString("DOCUMENTO_INPUT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Documento.
        /// </summary>
        internal static string DOCUMENTO_LOCALIZE_TITLE {
            get {
                return ResourceManager.GetString("DOCUMENTO_LOCALIZE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentos.
        /// </summary>
        internal static string DOCUMENTOS {
            get {
                return ResourceManager.GetString("DOCUMENTOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAMBIAR ESTO.
        /// </summary>
        internal static string DUMMY {
            get {
                return ResourceManager.GetString("DUMMY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ERROR_TITLE {
            get {
                return ResourceManager.GetString("ERROR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hipatia Gestor Documental.
        /// </summary>
        internal static string HIPATIA {
            get {
                return ResourceManager.GetString("HIPATIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F1 Ayuda.
        /// </summary>
        internal static string LEYENDA {
            get {
                return ResourceManager.GetString("LEYENDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered by iQ.
        /// </summary>
        internal static string POWEREDBY {
            get {
                return ResourceManager.GetString("POWEREDBY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipos de Documentos:.
        /// </summary>
        internal static string TIPO_DOCUMENTO_TITLE {
            get {
                return ResourceManager.GetString("TIPO_DOCUMENTO_TITLE", resourceCulture);
            }
        }
    }
}
