//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace moleQule.Face.Hipatia.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("moleQule.Face.Hipatia.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si cancela se perderán los últimos cambios realizados.
        ///                               ¿Cancelar?.
        /// </summary>
        internal static string CANCEL_CONFIRM {
            get {
                return ResourceManager.GetString("CANCEL_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrando conexión con el servidor....
        /// </summary>
        internal static string CLOSING_SERVER {
            get {
                return ResourceManager.GetString("CLOSING_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conectando con el servidor....
        /// </summary>
        internal static string CONNECTING_SERVER {
            get {
                return ResourceManager.GetString("CONNECTING_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al copiar el archivo. Inténtelo de nuevo por favor..
        /// </summary>
        internal static string COPY_ERROR {
            get {
                return ResourceManager.GetString("COPY_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe un elemento de esta entidad que está siendo editado. Para editar otro, por favor, cierre el anterior..
        /// </summary>
        internal static string CURRENT_EDITION {
            get {
                return ResourceManager.GetString("CURRENT_EDITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hay elementos en edición ¿Está seguro de que desea cerrar?.
        /// </summary>
        internal static string CURRENT_EDITION_CLOSE {
            get {
                return ResourceManager.GetString("CURRENT_EDITION_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar el elemento. Está siendo editado.
        /// </summary>
        internal static string CURRENT_EDITION_DELETE {
            get {
                return ResourceManager.GetString("CURRENT_EDITION_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Confirmar la eliminación del elemento seleccionado?.
        /// </summary>
        internal static string DELETE_CONFIRM {
            get {
                return ResourceManager.GetString("DELETE_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El borrado total de una empresa puede tardar algunos minutos.
        ///      ¿Confirmar la eliminación de la empresa seleccionada?.
        /// </summary>
        internal static string DELETE_CONFIRM_EMPRESA {
            get {
                return ResourceManager.GetString("DELETE_CONFIRM_EMPRESA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este documento no se encuentra asociado a más agentes. ¿Desea mantenerlo en el sistema?.
        /// </summary>
        internal static string DELETE_LAST_FILE {
            get {
                return ResourceManager.GetString("DELETE_LAST_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este documento ya se encuentra asociado al agente..
        /// </summary>
        internal static string DOC_REPEATED {
            get {
                return ResourceManager.GetString("DOC_REPEATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El documento está compartido con otros agentes.
        ///¿Desea continuar?.
        /// </summary>
        internal static string DOC_SHARED {
            get {
                return ResourceManager.GetString("DOC_SHARED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descargando actualización....
        /// </summary>
        internal static string DOWNLOADING_DATA {
            get {
                return ResourceManager.GetString("DOWNLOADING_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Descargando fichero desde el servidor....
        /// </summary>
        internal static string DOWNLOADING_FILE {
            get {
                return ResourceManager.GetString("DOWNLOADING_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copia de seguridad generada con éxito.
        /// </summary>
        internal static string DUMP_OK {
            get {
                return ResourceManager.GetString("DUMP_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creando copia de seguridad....
        /// </summary>
        internal static string DUMPING_BACKUP {
            get {
                return ResourceManager.GetString("DUMPING_BACKUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe otro elemento con ese códígo..
        /// </summary>
        internal static string DUPLICATED_CODE {
            get {
                return ResourceManager.GetString("DUPLICATED_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe dicho elemento en la lista..
        /// </summary>
        internal static string DUPLICATED_ELEMENT {
            get {
                return ResourceManager.GetString("DUPLICATED_ELEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjunto remito documento.
        ///
        ///{0}
        ///
        ///(Envío automático realizado con Facto)
        ///.
        /// </summary>
        internal static string EMAIL_ATTACHMENT_BODY {
            get {
                return ResourceManager.GetString("EMAIL_ATTACHMENT_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envío de documento.
        /// </summary>
        internal static string EMAIL_SUBJECT {
            get {
                return ResourceManager.GetString("EMAIL_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento enviado con éxito.
        /// </summary>
        internal static string EMAIL_SUCCESS {
            get {
                return ResourceManager.GetString("EMAIL_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede borrar la empresa activa..
        /// </summary>
        internal static string EMPRESA_NEEDED {
            get {
                return ResourceManager.GetString("EMPRESA_NEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El identificador no puede estar vacío..
        /// </summary>
        internal static string EMPTY_ID {
            get {
                return ResourceManager.GetString("EMPTY_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe introducir un precio..
        /// </summary>
        internal static string EMPTY_PRICE {
            get {
                return ResourceManager.GetString("EMPTY_PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe vacío.
        /// </summary>
        internal static string EMPTY_REPORT {
            get {
                return ResourceManager.GetString("EMPTY_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un campo requerido está vacío.
        /// </summary>
        internal static string EMPTY_REQUIRED_FIELD {
            get {
                return ResourceManager.GetString("EMPTY_REQUIRED_FIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string ENTERPRISE_MAX_LIMITED {
            get {
                return ResourceManager.GetString("ENTERPRISE_MAX_LIMITED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El número de empresas de la aplicación ha alcanzado el límite permitido..
        /// </summary>
        internal static string ENTERPRISE_MAX_LIMITED_NOTICE {
            get {
                return ResourceManager.GetString("ENTERPRISE_MAX_LIMITED_NOTICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario no autorizado para acceder a esta empresa.
        /// </summary>
        internal static string ENTERPRISE_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("ENTERPRISE_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo modificado contiene datos no válidos..
        /// </summary>
        internal static string INVALID_FORMAT {
            get {
                return ResourceManager.GetString("INVALID_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargando datos....
        /// </summary>
        internal static string LOADING_DATA {
            get {
                return ResourceManager.GetString("LOADING_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imposible bloquear el elemento seleccionado.
        ///Otro usuario está modificándolo en este momento. .
        /// </summary>
        internal static string LOCK_ERROR {
            get {
                return ResourceManager.GetString("LOCK_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar una fecha para el documento..
        /// </summary>
        internal static string MISSING_FECHA {
            get {
                return ResourceManager.GetString("MISSING_FECHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar una fecha de alta para el documento..
        /// </summary>
        internal static string MISSING_FECHA_ALTA {
            get {
                return ResourceManager.GetString("MISSING_FECHA_ALTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar un fichero.
        /// </summary>
        internal static string MISSING_FILE {
            get {
                return ResourceManager.GetString("MISSING_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar un tipo para el documento..
        /// </summary>
        internal static string MISSING_TIPO {
            get {
                return ResourceManager.GetString("MISSING_TIPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existen datos disponibles para realizar una selección específica para este tipo de informe..
        /// </summary>
        internal static string NO_DATA_ENTITY {
            get {
                return ResourceManager.GetString("NO_DATA_ENTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existen datos para imprimir..
        /// </summary>
        internal static string NO_DATA_REPORTS {
            get {
                return ResourceManager.GetString("NO_DATA_REPORTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario actual no puede ser eliminado.
        /// </summary>
        internal static string NO_DELETE_USER {
            get {
                return ResourceManager.GetString("NO_DELETE_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar un archivo..
        /// </summary>
        internal static string NO_FILE {
            get {
                return ResourceManager.GetString("NO_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El documento debe tener un nombre..
        /// </summary>
        internal static string NO_NAME {
            get {
                return ResourceManager.GetString("NO_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se han encontrado elementos coincidentes.
        /// </summary>
        internal static string NO_RESULTS {
            get {
                return ResourceManager.GetString("NO_RESULTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar un elemento de la lista.
        /// </summary>
        internal static string NO_SELECTED {
            get {
                return ResourceManager.GetString("NO_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione un tipo de identificador.
        /// </summary>
        internal static string NO_TYPE_SELECTED {
            get {
                return ResourceManager.GetString("NO_TYPE_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tiene permisos para hacer eso..
        /// </summary>
        internal static string NOT_ALLOWED {
            get {
                return ResourceManager.GetString("NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre del documento nuevo debe coincidir con el del documento a reemplazar..
        /// </summary>
        internal static string NOT_EQUAL_DOC_NAME {
            get {
                return ResourceManager.GetString("NOT_EQUAL_DOC_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las contraseñas introducidas no son iguales.
        /// </summary>
        internal static string NOT_EQUAL_PASS {
            get {
                return ResourceManager.GetString("NOT_EQUAL_PASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha sido posible realizar la operación.
        ///.
        /// </summary>
        internal static string OPERATION_ERROR {
            get {
                return ResourceManager.GetString("OPERATION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El fichero ya existe en el sistema. ¿Desea sobreescribirlo?..
        /// </summary>
        internal static string OVERWRITE_FILE {
            get {
                return ResourceManager.GetString("OVERWRITE_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha escrito una contraseña. ¿Está seguro de que desea que el usuario no posea contraseña?.
        /// </summary>
        internal static string PASSWORD_NULL {
            get {
                return ResourceManager.GetString("PASSWORD_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pendiente de guardar....
        /// </summary>
        internal static string PENDING_ON_SAVE {
            get {
                return ResourceManager.GetString("PENDING_ON_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe un documento con ese nombre..
        /// </summary>
        internal static string REPEATED_NAME {
            get {
                return ResourceManager.GetString("REPEATED_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardando....
        /// </summary>
        internal static string SAVING {
            get {
                return ResourceManager.GetString("SAVING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + = Agregar.
        /// </summary>
        internal static string STATUS_GENERICO {
            get {
                return ResourceManager.GetString("STATUS_GENERICO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subiendo fichero al servidor....
        /// </summary>
        internal static string UPLOADING_FILE {
            get {
                return ResourceManager.GetString("UPLOADING_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprobando permisos....
        /// </summary>
        internal static string VALIDATION_MSG {
            get {
                return ResourceManager.GetString("VALIDATION_MSG", resourceCulture);
            }
        }
    }
}
