//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.3082
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace moleQule.Face.Hipatia.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Paths {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Paths() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("moleQule.Face.Hipatia.Resources.Paths", typeof(Paths).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ../../Archivos de Programa/iQual Ingenieros/Hipatia 1.0/Resources/borrar_16.png.
        /// </summary>
        internal static string ELIMINAR_BT {
            get {
                return ResourceManager.GetString("ELIMINAR_BT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ../../Archivos de Programa/iQual Ingenieros/Hipatia 1.0/Resources/Modulos.ico.
        /// </summary>
        internal static string MODULO {
            get {
                return ResourceManager.GetString("MODULO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ../../Archivos de Programa/iQual Ingenieros/Hipatia 1.0/Resources/Nivel.ico.
        /// </summary>
        internal static string NIVEL {
            get {
                return ResourceManager.GetString("NIVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ../../Archivos de Programa/iQual Ingenieros/Hipatia 1.0/Resources/ordenar_16.png.
        /// </summary>
        internal static string ORDENAR_BT {
            get {
                return ResourceManager.GetString("ORDENAR_BT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ../../Archivos de Programa/iQual Ingenieros/Hipatia 1.0/Resources/Bloqueada.ico.
        /// </summary>
        internal static string PREGUNTA_BLOQUEADA {
            get {
                return ResourceManager.GetString("PREGUNTA_BLOQUEADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ../../Archivos de Programa/iQual Ingenieros/Hipatia 1.0/Resources/Disponible.ico.
        /// </summary>
        internal static string PREGUNTA_DISPONIBLE {
            get {
                return ResourceManager.GetString("PREGUNTA_DISPONIBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ../../Archivos de Programa/iQual Ingenieros/Hipatia 1.0/Resources/Reservada.ico.
        /// </summary>
        internal static string PREGUNTA_RESERVADA {
            get {
                return ResourceManager.GetString("PREGUNTA_RESERVADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ../../Archivos de Programa/iQual Ingenieros/Hipatia 1.0/Resources/Submodulos.ico.
        /// </summary>
        internal static string SUBMODULOS {
            get {
                return ResourceManager.GetString("SUBMODULOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ../../Archivos de Programa/iQual Ingenieros/Hipatia 1.0/Resources/submodulos_verde.ico.
        /// </summary>
        internal static string SUBMODULOS_LIBRE {
            get {
                return ResourceManager.GetString("SUBMODULOS_LIBRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ../../Archivos de Programa/iQual Ingenieros/Hipatia 1.0/Resources/ver_16.png.
        /// </summary>
        internal static string VER_BT {
            get {
                return ResourceManager.GetString("VER_BT", resourceCulture);
            }
        }
    }
}
